=== sawbona/sawbona-code/trunk/NetbeansProyects/P01AA/dtd/grupo.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT grupo (profesor, alumno+)>
<!ATTLIST grupo clave CDATA #REQUIRED>

<!ELEMENT profesor (nombre, apaterno, amaterno)>
<!ATTLIST profesor categoria (TC|AS) #REQUIRED>

<!ELEMENT alumno (nombre, apaterno, amaterno)>
<!ATTLIST alumno ncuenta CDATA #REQUIRED>

<!ELEMENT nombre   (#PCDATA)>
<!ELEMENT apaterno (#PCDATA)>
<!ELEMENT amaterno (#PCDATA)>

=== sawbona/sawbona-code/trunk/NetbeansProyects/P01AA/xml/grupo1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE grupo PUBLIC "-//FC//DTD grupo//EN" "../dtd/grupo.dtd">
<grupo clave="69">
	<profesor categoria="TC">
		<nombre>Gabriel</nombre>
		<apaterno>Garcia</apaterno>
		<amaterno>Marquez</amaterno>
	</profesor>
	<alumno ncuenta="0001">
		<nombre>Hugo</nombre>
		<apaterno>Mc Pato</apaterno>
		<amaterno>Rico</amaterno>
	</alumno>
	<alumno ncuenta="0010">
		<nombre>Paco</nombre>
		<apaterno>Mc Pato</apaterno>
		<amaterno>Rico</amaterno>
	</alumno>
	<alumno ncuenta="0011">
		<nombre>Luis</nombre>
		<apaterno>Mc Pato</apaterno>
		<amaterno>Rico</amaterno>
	</alumno>
</grupo>
